# https://ergogen.cache.works/
meta:
  version: 0.1.0
units:
  # Choc spacing
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # For preview only. We show slightly smaller to ID overlaps
  $default_width: cx-1
  $default_height: cy-1
points:
  rotate: -20
  key:
    padding: ky
    spread: kx
    tags:
      1u: true
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true

  zones:
    matrix:
      columns:
        outer:
          rows.mod.skip: true
          key:
            column_net: col_outer
            mirror.column_net: mirror_col_outer
        pinky:
          rows.mod.skip: true
          key:
            stagger: 3
            column_net: col_pinky
            mirror.column_net: mirror_col_pinky
        ring:
          key:
            stagger: 3
            column_net: col_ring
            mirror.column_net: mirror_col_ring
          rows:
            mod:
              column_net: col_pinky
              mirror.column_net: mirror_col_pinky
        middle:
          key:
            stagger: 3
            column_net: col_middle
            mirror.column_net: mirror_col_middle
          rows:
            mod:
              column_net: col_ring
              mirror.column_net: mirror_col_ring
        index:
          key:
            stagger: 3
            column_net: col_index
            mirror.column_net: mirror_col_index
          rows:
            mod:
              column_net: col_middle
              mirror.column_net: mirror_col_middle
        inner:
          rows.mod.skip: true
          key:
            stagger: -2
            column_net: col_inner
            mirror.column_net: mirror_col_inner
      rows:
        mod:
          row_net: row_mod
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
        num:
          row_net: row_num
      # Fix placement on KiCAD sheet
      anchor:
        shift: [100, -100]
    thumbfan:
      anchor:
        ref: matrix_inner_mod
        shift: [2, 8]
      columns:
        home:
          key:
            spread: 4+kx
            splay: -35
            origin: [-20.75, -19]
            column_net: col_index
            mirror.column_net: mirror_col_index
        far:
          key:
            spread: 21
            splay: -5
            origin: [-9.5, -9]
            column_net: col_inner
            mirror.column_net: mirror_col_inner
      rows:
        thumb:
          row_net: row_mod
  mirror:
    ref: matrix_inner_home
    distance: cx+60
outlines:
  raw:
    - what: rectangle
      where: true
      size: [2px, 2py]
      fillet: 4
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx - 0.5, ky - 0.5]
      #size: [kx, ky]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: thumbfan_far_thumb
          shift: [0.5px,-0.5py]
        - ref: matrix_index_mod
          shift: [0.25px, -0.65py]
        - ref: matrix_ring_mod
          shift: [-0.5px, -0.6py]
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.65py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.65py]

        - ref: mirror_matrix_inner_num
          shift: [0.5px, 0.65py]
        - ref: mirror_matrix_middle_num
          shift: [-0.5px, 0.65py]
        - ref: mirror_matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_ring_mod
          shift: [-0.5px, -0.6py]
        - ref: mirror_matrix_index_mod
          shift: [0.25px, -0.65py]
        - ref: mirror_thumbfan_far_thumb
          shift: [0.5px,-0.5py]
      fillet: 5
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  keyboard:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          hotswap: true
          reverse: false
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      board:
        what: promicro #footprints/waveshare_rp2040_zero
        # what: footprints/waveshare_rp2040_zero
        params:
          orientation: down
          # reversable: false # sic
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          rotate: -90
      oled:
        what: oled
        params:
          side: "F"
          SDA: P0
          SCL: P1
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [-6,-19]
          rotate: 90
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_outer_num]
          shift: [0.5kx, -0.3ky]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: [matrix_outer_bottom]
          shift: [0.5kx, -0.3ky]
      holeTopInnerLeft:
        what: mountinghole
        where:
          ref: [matrix_index_num]
          shift: [0.5kx, -0.4ky]
      holeBottomInnerLeft:
        what: mountinghole
        where:
          ref: [matrix_index_mod]
          shift: [0.5kx, -0.35ky]
      holeTopRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_outer_num]
          shift: [0.5kx, -0.3ky]
      holeBottomRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_outer_bottom]
          shift: [0.5kx, -0.3ky]
      holeTopInnerRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_index_num]
          shift: [0.5kx, -0.4ky]
      holeBottomInnerRight:
        what: mountinghole
        where:
          ref: [mirror_matrix_index_mod]
          shift: [0.5kx, -0.35ky]
